# This yml file is used to configure the evsim simulation

##############################################################################
# Simulation Parameters
##############################################################################
timescale: 15 # in minutes per step
simulation_length: 2688 #96*14 # in steps per simulation

##############################################################################
# Date:
##############################################################################
# Year, month, and day change after the envrionment has been reset
year: 2022 # 2015-2023
month: 1 # 1-12
day: 17 # 1-31

# Simulation Starting Time
hour: 6 # Simulation starting hour (24 hour format)
minute: 0 # Simulation starting minute (0-59)
# Hour and minute do not change after the environment has been reset

##############################################################################
# Charging Topology 
##############################################################################
v2g_enabled: False # True or False
number_of_charging_stations: 20000
number_of_transformers: 1
number_of_ports_per_cs: 3
# Provide path if you want to load a specific charging topology,
# else write None for a randomized one with the above parameters
charging_network_topology: None #./config_files/charging_topology_10.json
# Whether to have the transformer limits in power or current
transformer_max_power_or_current_mode: current # power or current
# Whether to include inflexible loads in the transformer power limit, such as residential loads
transformer_include_inflexible_loads: False # True or False

##############################################################################
# EV Specifications
##############################################################################
heterogeneous_ev_specs: False #if False, each EV has its own specifications
# such as battery capacity, charging rate, etc.

# EV Spawn Behavior
scenario: workplace # public, private, or workplace
spawn_multiplier: 2.5 # 1 is default, the higher the number the more EVs spawn
score_threshold: 0 # user satsifcation threshold for the game to end (0 -> never ends)

